(define (count-change amount)
  (define (cc-internal amt type-of-coins-left)
   (bkpt 'amt amt 'type-of-coins-left type-of-coins-left) 
   (cond (( = type-of-coins-left 0) 0)
          ((= amt 0) 1)
          ((< amt 0) 0)
      (else ( + (cc-internal amt (- type-of-coins-left 1))
                (cc-internal (- amt (denom type-of-coins-left))  type-of-coins-left )
            )
            )
    )
  )
  ; defines the change amount per index - similar to a hashtable
  (define (denom type-of-coins-left)
      (cond 
        ((= type-of-coins-left 1) 1)
        ((= type-of-coins-left 2) 5)
        ((= type-of-coins-left 3) 10)
        ((= type-of-coins-left 4) 25)
        ((= type-of-coins-left 5) 50)
      )
  )    

(cc-internal amount 5)
)